import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import ToastProvider from "@/utils/ToastProvier";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ToastProvider>
          <body className={inter.className}>{children}</body>
        </ToastProvider>
      </ReactQueryProvider>
    </html>
  );
}
